server:
  port: 9008

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://serviceregistry.bc61.tk/eureka/
  instance:
    hostname: user-service
