# deployment for spring boot microservice appointment-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  labels:
    role: appointment-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: appointment-service
  template:
    metadata:
      labels:
        role: appointment-service
    spec:
      containers:
        - name: appointment-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-appointment-service:v26
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: appointment-service
      
      imagePullSecrets:
        - name: my-docker-secret