# deployment for spring boot microservice cloud-gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  labels:
    role: cloud-gateway
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: cloud-gateway
  template:
    metadata:
      labels:
        role: cloud-gateway
    spec:
      containers:
        - name: cloud-gateway-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-cloud-gateway:v24
          imagePullPolicy: Always
          ports:
            - containerPort: 9191
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: cloud-gateway
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:32307/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
            - name: SPRING_DATASOURCE_PASSWORD
              value: Bootcamp@61
      
      imagePullSecrets:
        - name: my-docker-secret