# deployment for spring boot microservice cloud-gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  labels:
    role: cloud-gateway
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: cloud-gateway
  template:
    metadata:
      labels:
        role: cloud-gateway
    spec:
      containers:
        - name: cloud-gateway-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-cloud-gateway:v26
          imagePullPolicy: Always
          ports:
            - containerPort: 9191
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: cloud-gateway
      
      imagePullSecrets:
        - name: my-docker-secret