# deployment for spring boot microservice address-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-service
  labels:
    role: address-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: address-service
  template:
    metadata:
      labels:
        role: address-service
    spec:
      containers:
        - name: address-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-address-service:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 9001        
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: address-service
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret
---

# deployment for spring boot microservice appointment-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  labels:
    role: appointment-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: appointment-service
  template:
    metadata:
      labels:
        role: appointment-service
    spec:
      containers:
        - name: appointment-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-appointment-service:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: appointment-service
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret

---

# deployment for spring boot microservice card-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
  labels:
    role: card-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: card-service
  template:
    metadata:
      labels:
        role: card-service
    spec:
      containers:
        - name: card-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-card-service:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 9003
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: card-service

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
            
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            
            - name: SPRING_DATASOURCE_PASSWORD
              value: Bootcamp@61
      
      imagePullSecrets:
        - name: my-docker-secret
---

# deployment for spring boot microservice cloud-gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  labels:
    role: cloud-gateway
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: cloud-gateway
  template:
    metadata:
      labels:
        role: cloud-gateway
    spec:
      containers:
        - name: cloud-gateway-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-cloud-gateway:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 9191
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: cloud-gateway
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret
---

# deployment for spring boot microservice lab-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service
  labels:
    role: lab-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: lab-service
  template:
    metadata:
      labels:
        role: lab-service
    spec:
      containers:
        - name: lab-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-lab-service:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 9004
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: lab-service
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret


---
# deployment for spring boot microservice patient-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    role: patient-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: patient-service
  template:
    metadata:
      labels:
        role: patient-service
    spec:
      containers:
        - name: patient-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-patient-service:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 9005
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: patient-service
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret


---
# deployment for spring boot microservice service-registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    role: service-registry
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: service-registry
  template:
    metadata:
      labels:
        role: service-registry
    spec:
      containers:
        - name: service-registry-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-service-registry:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: service-registry
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret

---
# deployment for spring boot microservice test-lab-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-lab-service
  labels:
    role: test-lab-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: test-lab-service
  template:
    metadata:
      labels:
        role: test-lab-service
    spec:
      containers:
        - name: test-lab-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-test-lab-service:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 9006
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: test-lab-service
# spring.datasource.url=jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret
        
---
# deployment for spring boot microservice test-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  labels:
    role: test-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: test-service
  template:
    metadata:
      labels:
        role: test-service
    spec:
      containers:
        - name: test-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-test-service:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 9007
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: test-service
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret

---
# deployment for spring boot microservice user-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    role: user-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: user-service
  template:
    metadata:
      labels:
        role: user-service
    spec:
      containers:
        - name: user-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-user-service:v23
          imagePullPolicy: Always
          ports:
            - containerPort: 9008
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: user-service
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret