# deployment for spring boot microservice lab-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service
  labels:
    role: lab-service
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: lab-service
  template:
    metadata:
      labels:
        role: lab-service
    spec:
      containers:
        - name: lab-service-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-lab-service:v26
          imagePullPolicy: Always
          ports:
            - containerPort: 9004
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: lab-service
      
      imagePullSecrets:
        - name: my-docker-secret