# deployment for spring boot microservice service-registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    role: service-registry
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: service-registry
  template:
    metadata:
      labels:
        role: service-registry
    spec:
      containers:
        - name: service-registry-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-service-registry:v24
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://auth0-backend.spcluster.tk/eureka/

            - name: EUREKA_INSTANCE_HOSTNAME
              value: service-registry
      
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
            - name: SPRING_DATASOURCE_PASSWORD
              value: Bootcamp@61
      
      imagePullSecrets:
        - name: my-docker-secret