# deployment for spring boot microservice service-registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    role: service-registry
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: service-registry
  template:
    metadata:
      labels:
        role: service-registry
    spec:
      containers:
        - name: service-registry-container
          image: ghcr.io/ishtiaqsamdani007/auth0-bootcamp-backend-service-registry:v26
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: service-registry
      
      imagePullSecrets:
        - name: my-docker-secret