# deployment file for json server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server
  labels:
    role: json-server
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: json-server
  template:
    metadata:
      labels:
        role: json-server
    spec:
      containers:
        - name: json-server
          image: ghcr.io/ishtiaqsamdani007/auth0-json-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
      - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.186.244:31025/zemoso_diagnostics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
      imagePullSecrets:
        - name: my-docker-secret