# service for spring boot microservice address-service
apiVersion: v1
kind: Service
metadata:
  name: address-service
  labels:
    role: address-service
    env: demo
spec:
  ports:
    - port: 9001
  selector:
    role: address-service
---
# service for spring boot microservice appointment-service
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    role: appointment-service
    env: demo
spec:
  ports:
    - port: 9002
  selector:
    role: appointment-service
---
# service for spring boot microservice card-service
apiVersion: v1
kind: Service
metadata:
  name: card-service
  labels:
    role: card-service
    env: demo
spec:
  ports:
    - port: 9003
  selector:
    role: card-service
---

# service for spring boot microservice cloud-gateway
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway
  labels:
    role: cloud-gateway
    env: demo
spec:
  ports:
    - port: 9191
  selector:
    role: cloud-gateway

---
# service for spring boot microservice lab-service
apiVersion: v1
kind: Service
metadata:
  name: lab-service
  labels:
    role: lab-service
    env: demo
spec:
  ports:
    - port: 9004
  selector:
    role: lab-service
---
# service for spring boot microservice patient-service
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    role: patient-service
    env: demo
spec:
  ports:
    - port: 9005
  selector:
    role: patient-service
---
# service for spring boot microservice service-registry
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  labels:
    role: service-registry
    env: demo
spec:
  ports:
    - port: 8761
  selector:
    role: service-registry

---

# service for spring boot microservice test-lab-service
apiVersion: v1
kind: Service
metadata:
  name: test-lab-service
  labels:
    role: test-lab-service
    env: demo
spec:
  ports:
    - port: 9006
  selector:
    role: test-lab-service

---
# service for spring boot microservice test-service
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    role: test-service
    env: demo
spec:
  ports:
    - port: 9007
  selector:
    role: test-service

---
# service for spring boot microservice user-service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    role: user-service
    env: demo
spec:
  ports:
    - port: 9008
  selector:
    role: user-service