# service for spring boot microservice test-service
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    role: test-service
    env: demo
spec:
  ports:
    - port: 9007
  selector:
    role: test-service