apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: auth0-front.spcluster.tk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: auth0-json.spcluster.tk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: json-server
                port:
                  number: 3005
    - host: auth0-backend.spcluster.tk
      http:
        paths:
        - path: /$
          pathType: Exact
          backend:
            service:
              name: service-registry
              port:
                number: 8761
        - path: /eureka
          pathType: Prefix
          backend:
            service:
              name: service-registry
              port:
                number: 8761
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cloud-gateway
              port:
                number: 9191