apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: auth0-front.spcluster.tk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: auth0-json.spcluster.tk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: json-server
                port:
                  number: 3005