name: Deploy backend to GHCR and EKS

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'

env:
  GITHUB_USER: ishtiaqsamdani007

jobs:
  deploy_template:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '11'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Adding EKS cluster
        env: 
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
        run: |
          aws eks --region $aws_region update-kubeconfig --name $cluster_name

#   deploy_service:
#     needs: deploy_template
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build and Deploy the service
#         env:
#           SERVICE_NAME: ${{ matrix.service }}
#         run: |
#           pwd ls  
#           cd backend/${SERVICE_NAME}
#           mvn clean package -DskipTests
#           docker build -t ghcr.io/${{ env.GITHUB_USER }}/auth0-bootcamp-backend-${SERVICE_NAME}:v${{ github.run_number }} .
#           docker push ghcr.io/${{ env.GITHUB_USER }}/auth0-bootcamp-backend-${SERVICE_NAME}:v${{ github.run_number }}
#           kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}-container=ghcr.io/${{ env.GITHUB_USER }}/auth0-bootcamp-backend-${SERVICE_NAME}:v${{ github.run_number }}

  deploy_all:
    needs: deploy_template
    strategy:
      matrix:
        service: [address-service, user-service, appointment-service, card-service, cloud-gateway, lab-service, patient-service, service-registry, test-lab-service, test-service]
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy the service
        env:
            SERVICE_NAME: ${{ matrix.service }}
        run: |
            pwd 
            ls  
            cd backend/${SERVICE_NAME}
            mvn clean package -DskipTests
            docker build -t ghcr.io/${{ env.GITHUB_USER }}/auth0-bootcamp-backend-${SERVICE_NAME}:v${{ github.run_number }} .
            docker push ghcr.io/${{ env.GITHUB_USER }}/auth0-bootcamp-backend-${SERVICE_NAME}:v${{ github.run_number }}
            kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}-container=ghcr.io/${{ env.GITHUB_USER }}/auth0-bootcamp-backend-${SERVICE_NAME}:v${{ github.run_number }}






